DomainsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:provider.stage}-${self:service}-domains
    AttributeDefinitions:
      - AttributeName: cloud_id-app_id
        AttributeType: S
      - AttributeName: name
        AttributeType: S
      - AttributeName: id
        AttributeType: S
    KeySchema:
      - AttributeName: cloud_id-app_id
        KeyType: HASH
      - AttributeName: name
        KeyType: RANGE
    ProvisionedThroughput:
      ReadCapacityUnits: 5
      WriteCapacityUnits: 5
    GlobalSecondaryIndexes:
      - IndexName: cloud_id-app_id-id-index
        KeySchema:
          - AttributeName: cloud_id-app_id
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5