InboxMsgsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:service}-${self:provider.stage}-inbox-msgs
    AttributeDefinitions:
      - AttributeName: inbox_msg_id
        AttributeType: S
      - AttributeName: realm_id
        AttributeType: S
    KeySchema:
      - AttributeName: inbox_msg_id
        KeyType: HASH
      - AttributeName: realm_id
        KeyType: RANGE
    ProvisionedThroughput:
      ReadCapacityUnits: 5
      WriteCapacityUnits: 5
