ObjectsTable2:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:provider.stage}-${self:service}-${self:provider.environment.APP_ID_2}
    AttributeDefinitions:
      - AttributeName: domain_id
        AttributeType: S
      - AttributeName: id
        AttributeType: S
      - AttributeName: key
        AttributeType: S
    KeySchema:
      - AttributeName: domain_id
        KeyType: HASH
      - AttributeName: id
        KeyType: RANGE
    ProvisionedThroughput:
      ReadCapacityUnits: 5
      WriteCapacityUnits: 5
    GlobalSecondaryIndexes:
      - IndexName: domain_id-key-index
        KeySchema:
          - AttributeName: domain_id
            KeyType: HASH
          - AttributeName: key
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5