image: node:4.3

cache:
  paths:
    - node_modules/

stages:
  - test

mocha:
  stage: test
  tags:
    - node
  script:
    - npm install -g serverless@1.9.0
    - npm install --quiet
    - sls decrypt -s test -p $SECURE_PASSWORD
    - sls seed -s test
    - npm test
  artifacts:
    when: always
    paths:
      - mochawesome-reports/
  only:
    - develop
