account_id: 212868998188
api_gateway_invoke_url: https://oss-test.zyxel.ecoworkinc.com
app_id_1: 886386c171b7b53b5b9a8fed7f720daa96297225fdecd2e81b889a6be7abbf9d
app_id_2: 5fcdbbc1840e14832a5158a7ffa292b5c0028e135df5a6d5955c13325e464148
domains_limit: 2
pcloud_sso_user_info_url: https://mycloud-sso-alpha.zyxel.ecoworkinc.com/api/v1/my/info
security_group_id: sg-16cf5d72
subnet_id_1: subnet-5bd47870
subnet_id_2: subnet-942147e3
subnet_id_3: subnet-480d8911
x_api_key: wBJ57vwNfd55Hjvb1lF5H2CGrSZDe6MW9kCRxAxV
content_type: application/x-www-form-urlencoded
sqs_url: https://sqs.us-east-1.amazonaws.com/212868998188/object-storage-service-test-jobs
sqs_visibility_timeout: 0
csv_file: ./mochawesome-reports/test-plan.csv
test_cloud_id: zLanZi_liQQ_N_xGLr5g8mw
test_app_id: 886386c171b7b53b5b9a8fed7f720daa96297225fdecd2e81b889a6be7abbf9d
test_access_token: 7eda6dd4de708b1886ed34f6c0460ffef2d9094e5052fb706ad7635cadb8ea8b
certificate_serial: 1002

