account_id: 212868998188
api_gateway_invoke_url: https://klinuggmyc.execute-api.us-east-1.amazonaws.com/alpha/v1
app_id: 7c9e131ae86c0692042354821f23526929922dae666746b61801d630b84c72b1
domains_limit: 500
pcloud_sso_user_info_url: https://mycloud-sso-alpha.zyxel.ecoworkinc.com/api/v1/my/info